### PR TITLE
Nameless 1.0.21 update. Fixed some terrible bugs!

### PR DESCRIPTION
**Pull request by birkhofflee**
Removed nano from the image
docker-compose re-structure to improve layer caching
Explicitly use mysql:5.7 for backend db

Edit: the commit message should be 1.0.21 update instead of 1.0.16. Sorry!

### CODE REVIEW

**Comment by birkhofflee** [comment]
I'll be merging in 7 days if no one sees any bugs!

**Comment by samerton** [comment]
Thanks for the updates!

One small thing I can spot is that the PHP `mcrypt` extension is no longer required (from [line 12 of Dockerfile](https://github.com/NamelessMC/Nameless-Docker/pull/1/files#diff-28b3886804b6c975a958b69b941ea9afR12)) :)

**Comment by birkhofflee** [comment]
@samerton Should this be fine?

**Comment by samerton** [comment]
Thanks, looks great to me

**Pull request merged**
